services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: micronews
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  news-service:
    build:
      context: ./news-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=micronews
      - DATABASE_URL=postgres://postgres:postgres@db:5432/micronews?sslmode=disable

  comment-service:
    build:
      context: ./comment-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=micronews
      - DATABASE_URL=postgres://postgres:postgres@db:5432/micronews?sslmode=disable

  censor-service:
    build:
      context: ./censor-service

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8001"
    depends_on:
      - news-service
      - comment-service
      - censor-service

volumes:
  pgdata:
